"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Activity, ArrowUpRight, Bell, BookOpen, BriefcaseBusiness, CalendarDays,
  ChevronDown, CircleHelp, Clock3, FileCheck2, FileText, Gauge, GraduationCap,
  LayoutDashboard, Menu, MessageSquareText, MoreHorizontal, Network, Search,
  Settings, ShieldCheck, Sparkles, Target, UserRound, Users, X, Zap
} from "lucide-react";

type Summary = { employees: number; skills_mapped: number; skills_gaps: number; training_needs: number; critical_skill_risks: number; internal_talent_matches: number };
const fallback: Summary = { employees: 486, skills_mapped: 1284, skills_gaps: 37, training_needs: 28, critical_skill_risks: 7, internal_talent_matches: 16 };

const nav = [
  { label: "Overview", icon: LayoutDashboard }, { label: "Employees", icon: Users },
  { label: "Skill DNA", icon: Network }, { label: "Career development", icon: Target },
  { label: "Training & CPD", icon: GraduationCap }, { label: "Performance", icon: Gauge },
  { label: "Leave & attendance", icon: CalendarDays }, { label: "Recruitment", icon: BriefcaseBusiness },
  { label: "Compliance", icon: ShieldCheck }, { label: "Documents", icon: FileText }
];
const trend = [54, 61, 57, 69, 73, 81, 78, 91, 88, 97, 94, 100];

export default function Home() {
  const [active, setActive] = useState("Overview");
  const [summary, setSummary] = useState<Summary>(fallback);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/api/v1/dashboard/summary`)
      .then((response) => response.ok ? response.json() : null)
      .then((data) => data && setSummary(data))
      .catch(() => undefined);
  }, []);

  const today = useMemo(() => new Intl.DateTimeFormat("en-GB", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date()), []);

  return (
    <main className="flex min-h-screen bg-canvas">
      {mobileOpen && <button aria-label="Close navigation" onClick={() => setMobileOpen(false)} className="fixed inset-0 z-20 bg-ink/30 lg:hidden" />}
      <aside className={`fixed inset-y-0 left-0 z-30 flex w-[248px] flex-col border-r border-line bg-white px-4 py-6 transition-transform lg:static lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
        <div className="mb-8 flex items-center justify-between px-2">
          <div className="flex items-center gap-2.5"><span className="grid h-9 w-9 place-items-center rounded-xl bg-brand text-xl font-extrabold text-white">Z</span><div><p className="font-display text-[15px] font-extrabold leading-none text-ink">ZamConnect</p><p className="mt-1 text-[9px] font-bold tracking-[.25em] text-brand">PEOPLE</p></div></div>
          <button onClick={() => setMobileOpen(false)} className="text-slate-400 lg:hidden"><X size={18} /></button>
        </div>
        <div className="mb-6 rounded-xl bg-slate-50 p-3"><p className="eyebrow mb-2">Workspace</p><button className="flex w-full items-center justify-between text-left text-sm font-bold text-ink"><span className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#dce9ff] text-xs font-bold text-brand">ZC</span>Zambia HQ</span><ChevronDown size={15} className="text-muted" /></button></div>
        <nav className="space-y-1">{nav.map(({ label, icon: Icon }) => <button key={label} onClick={() => { setActive(label); setMobileOpen(false); }} className={`nav-item ${active === label ? "active" : ""}`}><Icon size={17} strokeWidth={active === label ? 2.5 : 2} />{label}{label === "Compliance" && <span className="ml-auto h-2 w-2 rounded-full bg-amber-400" />}</button>)}</nav>
        <div className="mt-auto space-y-1 border-t border-line pt-4"><button className="nav-item"><Settings size={17} />Settings</button><button className="nav-item"><CircleHelp size={17} />Help centre</button><div className="mt-5 flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#dce9ff] text-xs font-bold text-brand">KM</span><div className="min-w-0"><p className="truncate text-xs font-bold">Kunda Mwansa</p><p className="truncate text-[11px] text-muted">HR Administrator</p></div><MoreHorizontal size={16} className="ml-auto text-muted" /></div></div>
      </aside>
      <section className="min-w-0 flex-1">
        <header className="flex h-[76px] items-center justify-between border-b border-line bg-white px-5 sm:px-8"><div className="flex items-center gap-3"><button onClick={() => setMobileOpen(true)} className="text-ink lg:hidden"><Menu size={22} /></button><div className="relative hidden sm:block"><Search size={17} className="absolute left-3 top-2.5 text-muted" /><input onFocus={() => setSearchOpen(true)} onBlur={() => setSearchOpen(false)} placeholder="Search people, skills, roles..." className="h-10 w-64 rounded-xl bg-slate-50 pl-10 pr-3 text-sm outline-none ring-brand/20 transition focus:ring-2" />{searchOpen && <div className="absolute top-12 z-10 w-64 rounded-xl border border-line bg-white p-3 text-xs text-muted shadow-soft">Try searching for an employee or skill</div>}</div><span className="rounded-lg bg-blue-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-brand sm:hidden">ZC</span></div><div className="flex items-center gap-4"><button className="relative text-muted"><Bell size={19} /><span className="absolute -right-1 -top-1 h-2 w-2 rounded-full bg-rose-400 ring-2 ring-white" /></button><div className="hidden h-6 w-px bg-line sm:block" /><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#e7e1ff] text-xs font-bold text-lilac">KM</span><span className="hidden text-sm font-bold sm:block">Kunda Mwansa</span><ChevronDown size={14} className="text-muted" /></div></div></header>
        <div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8 lg:px-10"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow mb-2">{today}</p><h1 className="font-display text-2xl font-extrabold tracking-tight text-ink sm:text-3xl">Good morning, Kunda <span className="inline-block">👋</span></h1><p className="mt-1 text-sm text-muted">Here is what is happening across your workforce.</p></div><button className="flex w-fit items-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-bold text-white shadow-lg shadow-brand/20 transition hover:bg-blue-700"><Sparkles size={16} />Ask NALA</button></div>
          <div className="mb-6 flex items-center gap-3 rounded-2xl border border-blue-100 bg-gradient-to-r from-[#edf4ff] to-[#f7f4ff] p-4 sm:p-5"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-white text-brand shadow-sm"><Zap size={19} fill="currentColor" /></div><div className="min-w-0 flex-1"><p className="text-sm font-bold text-ink">Your workforce intelligence dashboard is ready</p><p className="mt-0.5 truncate text-xs text-muted">Turn people data into a clearer view of your organisation's skills and opportunities.</p></div><button className="hidden text-xs font-bold text-brand sm:block">Explore intelligence <ArrowUpRight size={14} className="ml-1 inline" /></button></div>
          <div className="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total workforce" value={summary.employees.toLocaleString()} change="+12.4%" note="vs last month" icon={<Users size={18} />} tone="blue" /><Metric label="Skills mapped" value={summary.skills_mapped.toLocaleString()} change="+8.7%" note="vs last month" icon={<Network size={18} />} tone="purple" /><Metric label="Skills coverage" value="78%" change="+4.2%" note="vs last month" icon={<Activity size={18} />} tone="green" /><Metric label="Training completion" value="84%" change="+6.1%" note="vs last month" icon={<GraduationCap size={18} />} tone="amber" /></div>
          <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><section className="card p-5 sm:p-6"><CardTitle title="Workforce capability" action="View intelligence" /><div className="mt-6 grid gap-7 sm:grid-cols-[190px_1fr] sm:items-center"><div className="relative mx-auto grid h-44 w-44 place-items-center rounded-full" style={{ background: "conic-gradient(#3265e6 0 78%, #dce8ff 78% 100%)" }}><div className="grid h-32 w-32 place-items-center rounded-full bg-white text-center"><div><p className="font-display text-3xl font-extrabold">78<span className="text-lg">%</span></p><p className="text-[11px] text-muted">overall coverage</p></div></div></div><div className="space-y-4"><Capability color="bg-brand" label="Critical skills covered" value="91%" /><Capability color="bg-lilac" label="Emerging skills" value="64%" /><Capability color="bg-amber-400" label="Skills gaps identified" value={`${summary.skills_gaps}`} /><div className="mt-5 rounded-xl bg-[#f7f9fc] p-3 text-xs leading-5 text-muted"><Sparkles size={14} className="mr-1 inline text-brand" />NALA found <strong className="text-ink">7 critical skill risks</strong> that may affect your 2026 workforce plan.</div></div></div></section><section className="card p-5 sm:p-6"><CardTitle title="Priority actions" action="View all" /><div className="mt-5 space-y-2"><Action icon={<Clock3 size={16} />} title="Leave requests" detail="4 requests need your review" tone="blue" /><Action icon={<FileCheck2 size={16} />} title="Compliance review" detail="3 policies are due this month" tone="amber" /><Action icon={<GraduationCap size={16} />} title="Training certificates" detail="8 certificates expire soon" tone="purple" /><Action icon={<MessageSquareText size={16} />} title="Employee feedback" detail="12 new workplace signals" tone="green" /></div></section></div>
          <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><section className="card overflow-hidden p-5 sm:p-6"><CardTitle title="Workforce trends" action="Last 6 months ·⌄" /><div className="mt-7 flex h-48 gap-3"><div className="flex flex-col justify-between pb-5 text-[10px] text-muted"><span>500</span><span>400</span><span>300</span><span>200</span><span>100</span></div><div className="relative flex flex-1 items-end justify-between gap-1 border-b border-l border-line bg-[linear-gradient(to_bottom,transparent_24%,#edf1f6_25%,transparent_26%,transparent_49%,#edf1f6_50%,transparent_51%,transparent_74%,#edf1f6_75%,transparent_76%)] px-2">{trend.map((height, index) => <div key={index} className="group relative flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-gradient-to-t from-[#bcd3ff] to-brand transition group-hover:from-brand" style={{ height: `${height}%` }} /><span className="absolute -bottom-6 w-full text-center text-[10px] text-muted">{["Apr", "", "May", "", "Jun", "", "Jul", "", "Aug", "", "Sep", ""][index]}</span></div>)}</div></div></section><section className="card p-5 sm:p-6"><CardTitle title="Recent activity" action="View all" /><div className="mt-5 space-y-4"><Activity initials="TM" title="Thandi M. completed" text="Data Analytics training" time="12 min ago" color="bg-[#dce9ff] text-brand" /><Activity initials="JM" title="Joseph M. submitted" text="a leave request" time="1 hr ago" color="bg-[#e7e1ff] text-lilac" /><Activity initials="SK" title="Sarah K. updated" text="her employee passport" time="3 hrs ago" color="bg-[#d9f5ed] text-mint" /></div></section></div>
        </div>
      </section>
    </main>
  );
}

function Metric({ label, value, change, note, icon, tone }: { label: string; value: string; change: string; note: string; icon: React.ReactNode; tone: string }) { return <div className="card p-5"><div className="flex items-start justify-between"><span className={`grid h-9 w-9 place-items-center rounded-xl ${tone === "blue" ? "bg-blue-50 text-brand" : tone === "purple" ? "bg-purple-50 text-lilac" : tone === "green" ? "bg-emerald-50 text-mint" : "bg-amber-50 text-amber-600"}`}>{icon}</span><span className="rounded-full bg-emerald-50 px-2 py-1 text-[10px] font-bold text-mint">{change}</span></div><p className="mt-5 text-xs font-medium text-muted">{label}</p><p className="mt-1 font-display text-2xl font-extrabold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-muted">{note}</p></div> }
function CardTitle({ title, action }: { title: string; action: string }) { return <div className="flex items-center justify-between"><h2 className="font-display text-base font-extrabold">{title}</h2><button className="text-xs font-bold text-brand hover:underline">{action} <ArrowUpRight size={13} className="ml-0.5 inline" /></button></div> }
function Capability({ color, label, value }: { color: string; label: string; value: string }) { return <div className="flex items-center gap-3 text-sm"><span className={`h-2.5 w-2.5 rounded-full ${color}`} /><span className="flex-1 text-muted">{label}</span><strong className="text-ink">{value}</strong></div> }
function Action({ icon, title, detail, tone }: { icon: React.ReactNode; title: string; detail: string; tone: string }) { return <button className="flex w-full items-center gap-3 rounded-xl p-2 text-left transition hover:bg-slate-50"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-xl ${tone === "blue" ? "bg-blue-50 text-brand" : tone === "purple" ? "bg-purple-50 text-lilac" : tone === "green" ? "bg-emerald-50 text-mint" : "bg-amber-50 text-amber-600"}`}>{icon}</span><span className="min-w-0 flex-1"><strong className="block text-xs">{title}</strong><small className="block truncate text-[11px] text-muted">{detail}</small></span><ArrowUpRight size={14} className="text-muted" /></button> }
function Activity({ initials, title, text, time, color }: { initials: string; title: string; text: string; time: string; color: string }) { return <div className="flex items-center gap-3"><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-[10px] font-bold ${color}`}>{initials}</span><div className="min-w-0 flex-1"><p className="truncate text-xs"><strong>{title}</strong> {text}</p><p className="mt-0.5 text-[10px] text-muted">{time}</p></div></div> }
