"use client";

import { useEffect, useState } from "react";

type Summary = { employees: number; skills_mapped: number; skills_gaps: number; training_needs: number; critical_skill_risks: number; internal_talent_matches: number };
const fallback: Summary = { employees: 250, skills_mapped: 1143, skills_gaps: 37, training_needs: 28, critical_skill_risks: 12, internal_talent_matches: 16 };
const nav = ["Overview", "Employees", "Skill DNA", "Career development", "Training & CPD", "Performance", "Leave & attendance", "Recruitment", "Compliance", "Documents"];

export default function Home() {
  const [active, setActive] = useState("Overview");
  const [summary, setSummary] = useState<Summary>(fallback);
  useEffect(() => { fetch(`${process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000"}/api/v1/dashboard/summary`).then(r => r.ok ? r.json() : null).then(data => data && setSummary(data)).catch(() => undefined); }, []);
  return <main className="shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">Z</span><div><strong>ZamConnect</strong><small>PEOPLE</small></div></div><div className="workspace"><span className="avatar">ZM</span><div><strong>Zambia Manufacturing</strong><small>Company workspace</small></div><span>⌄</span></div><nav>{nav.map(item => <button className={active === item ? "nav-item active" : "nav-item"} onClick={() => setActive(item)} key={item}><span className="nav-icon">{["Overview","Employees","Skill DNA","Career development","Training & CPD","Performance","Leave & attendance","Recruitment","Compliance","Documents"].indexOf(item) + 1}</span>{item}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><span className="nav-icon">?</span>Help centre</button><button className="nav-item"><span className="nav-icon">⚙</span>Settings</button></div></aside>
    <section className="content"><header><div><p className="eyebrow">WEDNESDAY, 23 SEPTEMBER 2026</p><h1>{active}</h1><p className="muted">Your organisation at a glance.</p></div><div className="header-actions"><button className="icon-button">⌕</button><button className="icon-button">♧<i /></button><div className="user"><span className="avatar coral">CM</span><div><strong>Chanda Mumba</strong><small>Company Administrator</small></div><span>⌄</span></div></div></header>
    <div className="banner"><div><span className="spark">✦</span><div><strong>Welcome to your workforce intelligence dashboard</strong><p>Build a clearer picture of your organisation's skills, people and potential.</p></div></div><button className="banner-button">Explore Skill DNA <span>→</span></button></div>
    <section className="metrics"><Metric label="Total workforce" value={summary.employees} change="+12.4%" tone="green" note="vs last month" /><Metric label="Skills mapped" value={summary.skills_mapped.toLocaleString()} change="+8.2%" tone="green" note="across your people" /><Metric label="Critical skill risks" value={summary.critical_skill_risks} change="Needs attention" tone="amber" note="skills with limited coverage" /><Metric label="Training needs" value={summary.training_needs} change="+4 this month" tone="purple" note="identified development gaps" /></section>
    <div className="grid"><section className="card capability"><CardTitle title="Workforce capability" action="View intelligence" /><div className="capability-body"><div className="donut"><div><strong>78%</strong><span>Skill coverage</span></div></div><div className="legend"><Legend color="blue" label="Skills mapped" value="1,143" /><Legend color="purple" label="Development gaps" value={summary.skills_gaps.toString()} /><Legend color="pale" label="Not yet mapped" value="22%" /></div></div><div className="insight"><span>✦</span><div><strong>Your workforce has strong potential</strong><p>Map 37 identified skill gaps to unlock more internal mobility.</p></div><button>→</button></div></section><section className="card actions"><CardTitle title="Priority actions" action="View all" /><Action icon="!" title="7 certifications expiring" detail="Within the next 30 days" tone="amber" /><Action icon="✓" title="12 performance reviews due" detail="Due this month" tone="blue" /><Action icon="↗" title="4 critical skill risks" detail="Require development plans" tone="purple" /><Action icon="+" title="3 new employees to onboard" detail="Started this week" tone="green" /></section></div>
    <div className="grid lower"><section className="card chart"><CardTitle title="Workforce trends" action="Last 6 months ·⌄" /><div className="chart-area"><div className="y-axis"><span>300</span><span>200</span><span>100</span><span>0</span></div><div className="bars">{[68,74,73,82,88,96].map((h,i)=><div className="bar-group" key={i}><div className="bar" style={{height:`${h}%`}} /><span>{["Apr","May","Jun","Jul","Aug","Sep"][i]}</span></div>)}</div></div></section><section className="card activity"><CardTitle title="Recent activity" action="View audit log" /><Activity initials="TM" title="Thandiwe Mulenga" text="completed HR Analytics training" time="18 min ago" color="blue" /><Activity initials="SK" title="Simon Kalaba" text="submitted a leave request" time="1 hr ago" color="purple" /><Activity initials="NM" title="Naomi Mwansa" text="updated their Skill DNA" time="3 hrs ago" color="coral" /></section></div>
    </section></main>;
}
function Metric({label,value,change,tone,note}:{label:string,value:number|string,change:string,tone:string,note:string}) { return <div className="metric"><span className="metric-label">{label}</span><strong>{value}</strong><div><span className={`pill ${tone}`}>{change}</span><small>{note}</small></div></div> }
function CardTitle({title,action}:{title:string,action:string}) { return <div className="card-title"><h2>{title}</h2><button>{action} →</button></div> }
function Legend({color,label,value}:{color:string,label:string,value:string}) { return <div className="legend-row"><span className={`dot ${color}`} />{label}<strong>{value}</strong></div> }
function Action({icon,title,detail,tone}:{icon:string,title:string,detail:string,tone:string}) { return <div className="action"><span className={`action-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><span className="arrow">→</span></div> }
function Activity({initials,title,text,time,color}:{initials:string,title:string,text:string,time:string,color:string}) { return <div className="activity-row"><span className={`avatar ${color}`}>{initials}</span><div><strong>{title}</strong><p>{text}</p></div><small>{time}</small></div> }
